### PR TITLE
MangaTaggerLib Rewrite + Fixes

### PR DESCRIPTION
**Pull request by jmeacoe**
Rewrote MangaTaggerLib to rely more heavily on the local mongodb tables before checking the API.

Additions:
- Added support for older revisions of MongoDB 4.4, this allows for mangatagger to be ran on more hardware options
- Added the ability to reattempt to tag a series if the destination files no longer exist
- Added proper rate limiting to API calls instead of waiting to receive an error

Fixes:
- Fixed reprocessing a file if it uses a different series name than the initial processed file.
- Fixed a bug for cover downloading if the series name had invalid file system characters.
- Fixed cbz files from being created with just comicinfo.xml and cover images if the file wasn't renamed and moved.
- Fixed cbz files from being renamed and moved if another process is still zipping them.
   *Please note this fix removed the ability to move files into the untagged folder to be automatically processed.  The App or docker would need to be reset to check for existing files.

### CODE REVIEW

**Comment by jmeacoe** [comment]
Also changed the destination to retain the Ch. for easier reading and parsing by applications. Adding to tests now.

**Comment by jmeacoe** [comment]
I now check to see if the file exists already at the location so I don't know how best to update these tests.  Can i spoof the file being created at the location already or is it best to remove these specific tests?

**Comment by jmeacoe** [comment]
I have no clue how to fix these unit tests.  The os commands aren't finding the files that are created as part of the tests.
They are legitimately failing at the OS command right before the expected response.

@ThePromidius  any ideas?
I've tried absolute paths and no dice.
I've tried open(,'w') instead of touch. 
I don't have a good grasp on the mock features for unit test but I went down a rabbit hole there.

**Comment by ThePromidius** [comment]
```# Check to see if the file exists at the old location before doing anything rash like deleting the new file.```
Line 205 in MangaTaggerLib 

You trying to check if the filename exists which fails i guess? This ends up with not moving the file.
Try using the function paramenter `current_file_path` which holds the whole path?
Not really sure what you try to accomplish there anyway.

Seems like too many changes all mixed up together. Maybe small focused changes would have been better.
Also not sure some changes would really be worth to merge. Thinking that they'd be better in the planned rewrite. I discussed this with bahn cann some time ago. Making changes on the current code is hard and makes it hard to read.

Try looking around that line i pointed out see if that makes any difference. Haven't had the time to properly review the pr. just took an overview.

**Pull request closed without merging**
